config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs/javascripts/jasmine_specs' if defined?(JasmineRails)
  root to: "todos#index"
  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def main
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:done, :name, :order)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="ng-vegas">
  <head>
    <base href="/">
    <title>NgVegasTalk</title>
    <%= stylesheet_link_tag    'application', media: {'all' => true} %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/todos/_form.html.haml
= form_for @todo do |f|
  - if @todo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
      %ul
        - @todo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :done
    = f.check_box :done
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :order
    = f.number_field :order
  .actions
    = f.submit 'Save'

app/views/todos/edit.html.haml
%h1 Editing todo

= render 'form'

= link_to 'Show', @todo
\|
= link_to 'Back', todos_path

app/views/todos/index.html.haml
%ng-view

app/views/todos/new.html.haml
%h1 New todo

= render 'form'

= link_to 'Back', todos_path

app/views/todos/show.html.haml
%p#notice= notice

%p
  %b Done:
  = @todo.done
%p
  %b Name:
  = @todo.name
%p
  %b Order:
  = @todo.order

= link_to 'Edit', edit_todo_path(@todo)
\|
= link_to 'Back', todos_path